sdkversion: 5.5.0
name: inventoryDemo
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt

iphone:
  configuration: Release
  sdk: latest
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.tautechnologies.inventorydemo
  BundleURLScheme: inventorydemo
  http_connection_domains: ["inventory-demo-rhoconnect.herokuapp.com", "taulogservice.herokuapp.com"]
  info_plist_data:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true
  extensions:
    - barcode

wp8:
  productid: '07c45400-ba39-0134-a27f-60f81db5e3c0'
  extensions:
    - enterprise-barcode

android:
  manifest_template: 'AndroidManifest.erb'
  version: 6.0
  abis:
    - x86
    - arm
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  extensions:
    - barcode
    #- enterprise-barcode
  android_title: 0

wm:
  extensions:
    - barcode
    - webkit
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

win32:
  deployqt: 1
  deploymsvc: 1
  extensions:
    - enterprise-barcode

extensions:
  - rhoconnect-client
  - mediacapture
  - signature

rhobundle:
  exclude_items:
  - thumb.db

 sailfish:
   configuration: Debug
   target: 'arm'
   device:
     type: real
     device_name: INOI R7 (ARM)
     user: nemo
     key: C:/SailfishOS/vmshare/ssh/private_keys/INOI_R7_(ARM)/nemo
     password:
     host: '192.168.1.66'
   extensions: ["mediacapture", "barcode", "signature", "rhoconnect-client"]

 paths:
   extensions: ["<you path here>/rhoconnect-client/ext"]