#sdk: "../rhodes"
sdkversion: 7.1.2
name: inventoryDemo
version: 1.0.3
vendor: rhomobile
build: release
applog: rholog.txt

iphone:
  configuration: Release
  sdk: latest
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.tautechnologies.inventorydemo
  BundleURLScheme: inventorydemo
  http_connection_domains: ["inventory-demo-rhoconnect.herokuapp.com", "taulogservice.herokuapp.com"]
  info_plist_data:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true
  extensions:
    - barcode
    - mediacapture
    - signature
    - rhoconnect-client

wp8:
  productid: '07c45400-ba39-0134-a27f-60f81db5e3c0'
  extensions:
    - enterprise-barcode
linux:
  extensions:
    - barcode
    - rhoconnect-client
    - mediacapture

android:
  manifest_template: 'AndroidManifest.erb'

  minSDK: 23
  targetSDK: 29
  #version: 6.0
  abis:
    - x86
    - arm
    - aarch64
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
  extensions:
    - barcode
    - mediacapture
    - signature
    - rhoconnect-client
    #- enterprise-barcode
    - rhoconnect-client
    - mediacapture
    - signature
  android_title: 0

wm:
  extensions:
    - barcode
    - webkit
    - rhoconnect-client
    - mediacapture
    - signature
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

win32:
  deployqt: 1
  deploymsvc: 1
  extensions:
    - enterprise-barcode

linux:
  extensions:
    - rhoconnect-client
    - mediacapture
    - signature


rhobundle:
  exclude_items:
  - thumb.db

sailfish:
  configuration: Debug
  target: 'arm'
  device:
    type: real
    device_name: INOI R7 (ARM)
    user: nemo
    key: C:/SailfishOS/vmshare/ssh/private_keys/INOI_R7_(ARM)/nemo
    #password: fxmnmzzcw
    host: '192.168.0.103'
  extensions: ["mediacapture", "barcode", "signature", "rhoconnect-client"]
#paths:
# extensions: ["../rhoconnect-client/ext"]

